import { Prisma } from "@prisma/client";

export var screen1 = [
            { id: 'A1',sold:false,type:"elite" },
            { id: 'A2',sold:false,type:"elite"  },
            { id: 'A3',sold:false,type:"elite"  },
            { id: 'A4',sold:false ,type:"elite" },
            { id: 'A5',sold:false ,type:"elite" },
            { id: 'A6',sold:false,type:"elite"  },
            { id: 'A7',sold:false,type:"elite"  },
            { id: 'A8',sold:false,type:"elite"  },
            { id: 'B1',sold:false,type:"elite"  },
            { id: 'B2',sold:false,type:"elite"  },
            { id: 'B3',sold:false,type:"elite"  },
            { id: 'B4',sold:false,type:"elite"  },
            { id: 'B5',sold:false,type:"elite"  },
            { id: 'B6',sold:false,type:"elite"  },
            { id: 'B7',sold:false,type:"elite"  },
            { id: 'B8',sold:false,type:"elite"  },
            { id: 'C1',sold:false,type:"gold"  },
            { id: 'C2',sold:false,type:"gold"  },
            { id: 'C3',sold:false,type:"gold"  },
            { id: 'C4',sold:false,type:"gold"  },
            { id: 'C5',sold:false,type:"gold"  },
            { id: 'C6',sold:false,type:"gold"  },
            { id: 'C7',sold:false,type:"gold"  },
            { id: 'C8',sold:false,type:"gold"  },
            { id: 'D1',sold:false,type:"gold"  },
            { id: 'D2',sold:false,type:"gold"  },
            { id: 'D3',sold:false,type:"gold"  },
            { id: 'D4',sold:false,type:"gold"  },
            { id: 'D5',sold:false,type:"gold"  },
            { id: 'D6',sold:false,type:"gold"  },
            { id: 'D7',sold:false,type:"gold"  },
            { id: 'D8',sold:false,type:"gold"  },
            { id: 'E1',sold:false,type:"gold"  },
            { id: 'E2',sold:false,type:"gold"  },
            { id: 'E3',sold:false,type:"gold"  },
            { id: 'E4',sold:false,type:"gold"  },
            { id: 'E5',sold:false,type:"gold"  },
            { id: 'E6',sold:false,type:"gold"  },
            { id: 'E7',sold:false,type:"gold"  },
            { id: 'E8',sold:false,type:"gold"  },
            { id: 'F1',sold:false,type:"silver"  },
            { id: 'F2',sold:false,type:"silver"  },
            { id: 'F3',sold:false,type:"silver"  },
            { id: 'F4',sold:false,type:"silver"  },
            { id: 'F5',sold:false,type:"silver"  },
            { id: 'F6',sold:false,type:"silver"  },
            { id: 'F7',sold:false,type:"silver"  },
            { id: 'F8',sold:false,type:"silver"  },
            { id: 'G1',sold:false,type:"silver"  },
            { id: 'G2',sold:false,type:"silver"  },
            { id: 'G3',sold:false,type:"silver"  },
            { id: 'G4',sold:false,type:"silver"  },
            { id: 'G5',sold:false,type:"silver"  },
            { id: 'G6',sold:false,type:"silver"  },
            { id: 'G7',sold:false,type:"silver"  },
            { id: 'G8',sold:false,type:"silver"  },
            { id: 'H1',sold:false,type:"budget"  },
            { id: 'H2',sold:false,type:"budget"  },
            { id: 'H3',sold:false,type:"budget"  },
            { id: 'H4',sold:false,type:"budget"  },
            { id: 'H5',sold:false,type:"budget"  },
            { id: 'H6',sold:false,type:"budget"  },
            { id: 'H7',sold:false,type:"budget"  },
            { id: 'H8',sold:false,type:"budget"  },
] as Prisma.JsonArray;

export let row =[
            {
                "n": "CLASSIC (60.12)",
                "s": [],
                "t": "area"
            },
            {
                "n": "A",
                "s": [
                    {
                        "displaynumber": "",
                        "b": "0000000002|1|1|17",
                        "c": "0000000002",
                        "s": 2,
                        "sn": "A1",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000002|1|1|16",
                        "c": "0000000002",
                        "s": 2,
                        "sn": "A2",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000002|1|1|15",
                        "c": "0000000002",
                        "s": 2,
                        "sn": "A3",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000002|1|1|14",
                        "c": "0000000002",
                        "s": 2,
                        "sn": "A4",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000002|1|1|13",
                        "c": "0000000002",
                        "s": 2,
                        "sn": "A5",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumberP": "",
                        "b": "0000000002|1|1|12",
                        "c": "0000000002",
                        "s": 2,
                        "sn": "A6",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000002|1|1|11",
                        "c": "0000000002",
                        "s": 2,
                        "sn": "A7",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000002|1|1|10",
                        "c": "0000000002",
                        "s": 2,
                        "sn": "A8",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000002|1|1|7",
                        "c": "0000000002",
                        "s": 2,
                        "sn": "A9",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000002|1|1|6",
                        "c": "0000000002",
                        "s": 2,
                        "sn": "A10",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000002|1|1|5",
                        "c": "0000000002",
                        "s": 2,
                        "sn": "A11",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000002|1|1|4",
                        "c": "0000000002",
                        "s": 2,
                        "sn": "A12",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000002|1|1|3",
                        "c": "0000000002",
                        "s": 2,
                        "sn": "A13",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000002|1|1|2",
                        "c": "0000000002",
                        "s": 2,
                        "sn": "A14",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000002|1|1|1",
                        "c": "0000000002",
                        "s": 2,
                        "sn": "A15",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    }
                ],
                "t": "seats"
            },
            {
                "n": "PRIME (190.78)",
                "s": [],
                "t": "area"
            },
            {
                "n": "B",
                "s": [
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|9|17",
                        "c": "0000000003",
                        "s": 1,
                        "sn": "B1",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|9|16",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "B2",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|9|15",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "B3",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|9|14",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "B4",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|9|13",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "B5",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|9|12",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "B6",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|9|11",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "B7",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|9|10",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "B8",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|9|7",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "B9",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|9|6",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "B10",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|9|5",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "B11",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|9|4",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "B12",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|9|3",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "B13",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|9|2",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "B14",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|9|1",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "B15",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    }
                ],
                "t": "seats"
            },
            {
                "n": "C",
                "s": [
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|8|17",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "C1",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|8|16",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "C2",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|8|15",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "C3",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|8|14",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "C4",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|8|13",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "C5",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|8|12",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "C6",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|8|11",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "C7",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|8|10",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "C8",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|8|7",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "C9",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|8|6",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "C10",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|8|5",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "C11",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|8|4",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "C12",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|8|3",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "C13",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|8|2",
                        "c": "0000000003",
                        "s": 1,
                        "sn": "C14",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|8|1",
                        "c": "0000000003",
                        "s": 1,
                        "sn": "C15",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    }
                ],
                "t": "seats"
            },
            {
                "n": "D",
                "s": [
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|7|17",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "D1",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|7|16",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "D2",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|7|15",
                        "c": "0000000003",
                        "s": 1,
                        "sn": "D3",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|7|14",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "D4",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|7|13",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "D5",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|7|12",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "D6",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|7|11",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "D7",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|7|10",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "D8",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|7|7",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "D9",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|7|6",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "D10",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|7|5",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "D11",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|7|4",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "D12",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|7|3",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "D13",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|7|2",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "D14",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|7|1",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "D15",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    }
                ],
                "t": "seats"
            },
            {
                "n": "E",
                "s": [
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|6|17",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "E1",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|6|16",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "E2",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|6|15",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "E3",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|6|14",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "E4",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|6|13",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "E5",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|6|12",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "E6",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|6|11",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "E7",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|6|10",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "E8",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|6|7",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "E9",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|6|6",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "E10",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|6|5",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "E11",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|6|4",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "E12",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|6|3",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "E13",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|6|2",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "E14",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|6|1",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "E15",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    }
                ],
                "t": "seats"
            },
            {
                "n": "F",
                "s": [
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|5|17",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "F1",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|5|16",
                        "c": "0000000003",
                        "s": 1,
                        "sn": "F2",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|5|15",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "F3",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|5|14",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "F4",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|5|13",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "F5",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|5|12",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "F6",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|5|11",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "F7",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|5|10",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "F8",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|5|7",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "F9",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|5|6",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "F10",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|5|5",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "F11",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|5|4",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "F12",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|5|3",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "F13",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|5|2",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "F14",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|5|1",
                        "c": "0000000003",
                        "s": 1,
                        "sn": "F15",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    }
                ],
                "t": "seats"
            },
            {
                "n": "G",
                "s": [
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|4|17",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "G1",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|4|16",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "G2",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|4|15",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "G3",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|4|14",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "G4",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|4|13",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "G5",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|4|12",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "G6",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|4|11",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "G7",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|4|10",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "G8",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|4|7",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "G9",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|4|6",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "G10",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|4|5",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "G11",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|4|4",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "G12",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|4|3",
                        "c": "0000000003",
                        "s": 1,
                        "sn": "G13",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|4|2",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "G14",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|4|1",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "G15",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    }
                ],
                "t": "seats"
            },
            {
                "n": "H",
                "s": [
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|3|17",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "H1",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|3|16",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "H2",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|3|15",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "H3",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|3|14",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "H4",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|3|13",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "H5",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|3|12",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "H6",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|3|11",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "H7",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|3|10",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "H8",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|3|7",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "H9",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|3|6",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "H10",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|3|5",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "H11",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|3|4",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "H12",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|3|3",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "H13",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|3|2",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "H14",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|3|1",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "H15",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    }
                ],
                "t": "seats"
            },
            {
                "n": "J",
                "s": [
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|2|17",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "J1",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|2|16",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "J2",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|2|15",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "J3",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|2|14",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "J4",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|2|13",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "J5",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|2|12",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "J6",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|2|11",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "J7",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|2|10",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "J8",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|2|7",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "J9",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|2|6",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "J10",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|2|5",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "J11",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|2|4",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "J12",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|2|3",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "J13",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|2|2",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "J14",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|2|1",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "J15",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    }
                ],
                "t": "seats"
            },
            {
                "n": "K",
                "s": [
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|1|17",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "K1",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|1|16",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "K2",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|1|15",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "K3",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|1|14",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "K4",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|1|13",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "K5",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|1|12",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "K6",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|1|11",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "K7",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": "0000000003|2|1|10",
                        "c": "0000000003",
                        "s": 2,
                        "sn": "K8",
                        "en": true,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    },
                    {
                        "displaynumber": "",
                        "b": null,
                        "c": null,
                        "s": 0,
                        "sn": null,
                        "en": false,
                        "hc": false,
                        "bu": false,
                        "st": 0,
                        "cos": false
                    }
                ],
                "t": "seats"
            }
        ] as Prisma.JsonArray